$ANSIBLE_VAULT;1.1;AES256
66613962616533363434313033633437616262633836356635336663376438316336366231656363
3238303535663365373462393366363564613135393935320a333439323865653135653130663461
33363030333835376630646262643061306437643166653831313938343535323231343336623133
3233616235346533320a306534393230373738663338346663383234316565373831336363633565
39643265323661666132653130383633666432363665616637346535313766383038316338363333
32363162393035323639393831313236373566306137633663666566646165343862306563363835
34646434653536383866323966316435623934383364343534343363636230653830356139346538
36373533613937313333343436663136663135646535376536303766363739613062626234336164
31666132313061353764356433323535663835326638366332623936306436326461353465663236
34643564646432653837303632666631333332633132643334326163393734656434396332393230
63626236383639336237636163653837666635373162633664373039656132663733353166393666
37303730646534353764383361373137643736623436623464373039376639393430376438316435
3539
